sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
- cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: FUsoEm23/kAXjHJbENtFNzOkdWvWlJT3Yow8Otw/J+ETJnjNxsBMvQ4lmysz5x3i0VNYY3VKs//FzQccwg2BThFIlSn0Ttc6K74KbjgQvb+25MIY4XAX1Y3ly2FRloUPgU1RBoqH5LLmy8KqljcnOoCRPf9RpTj9wa5SxbLnu1FVE2cHug8Lps2UowiT39TAb4BfdKVW8soMotjmVPo0eHsQ9sypNbse+KWLOi662uKp3bsH3qvU4N/zmZRDOU3rE24sOOUctsLmt8BPdVABFA9bNCMmk+jyN3Yb8KtuASlQjHpx4e1s+x3M1jEDPAT+GQxon7K2785DmvhxqQrnacbCsSmmB1wvKE7pSPpvfXiW/MVAnaV1/u3qmEhLFYY9OShh+qvG/GaUKyzimqCXoy/Ir1dw3NaPMCmPI2ovidti6CBofdhPLGDXwoil+jh+YnlPlOFBdxme2jvp3cHge1LqrmC1qNxNyKxoMJ6B+knyEYkaPWLa/3Xi0ABbMhWnfRcPxb19o1e7il6QmdcQkDaVszCzvceJZnpJPgbquPM3luMtynlGU349rpSIhJIbNYyOvKoKqSow/Kkw87ZccdlFBPLyjtZgxO+JVu4BzgMkN75tbHcFzcMNvKh+5d9wh7jpn2Kvr6fDekgCqySYRpy1efGMd5pFEwFpW13I2ic=
  - secure: pu1usejknvsagOlCgitAqx1mIREQ78N6w6PN7ka3vzvJIgT8lMbbu8EIOMI6BNmJ9K4mBUNpciuNjC7TMjzgkFMPm/s57nAgsyOkcM5gSV+uRNBprdGarZuK32YrviZBHWF9d8WLXyMoFKxAHCkn1rH1sAm2CRrSsrl/7DTQE581L3dndw3J2t/B0pGCfr5AdbgyJ9ciffQN3L/JDrTj0NmiMW1e3I9MbjXLVGP9g+JHFgrq9I8PmrruJjKCji+pZ9YBLTbgdYk2ILT4vuOM02DFiuN6Yb+4Ze+pqePu0sIT9pptffqltPu4QRaVCloiEr6WQd1n2nrcswnJptg72EpZBTPCyYC8joSv7o2bfJO3VeZ74SgHZi0YI7ErJksKJ8tFfHRoBjMeRsPyPK200vbceVzD1TcgjPRwCclBScr84jgrnn3l/OdqmLyD2gLahk+NV5hb0Zdltq+FVQ+2OFvhAddPp+AZfjmaU21jGiJzzmLU250k8kbQzKWHwbHWVpMUfjBaJejHNpgtBaLTCFJtWanS1HpxDfOghbzFNSlPsqZxL6x4Z5Z0tjiX6W4rs76MudbTHiTGiVLbIzRDczycT9X9c+hrWDDBiyOUiKNSoAbCyNlJj3xre2J6y7H2FKnUHCCxbyuvgK1/Fgplb2YTb0fzHGDjYe1Ce5C7NnA=
